// <auto-generated />
namespace Payroll_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class employeedata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(employeedata));
        
        string IMigrationMetadata.Id
        {
            get { return "202004020642006_employeedata"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
